### ISSUE TITLE
Space in directory stops files from listing

### ISSUE THREAD

**Issue by gedm** [AngeIII/simple-file-manager#2]
Hello,
Thanks for the enhancements. I notice in your fork and the main script, when the directory contains a space, the contents of the directly aren't listed when the directory is viewed.
I'm happy to fix it but I'm not sure where to start.  I have basic PHP experience, can you suggest what I should look for to change the code?
Thanks

**Comment by pavelthq** [comment]
Sorry for delayed response, didn't received any notifications. Will check this soon.

**Comment by gedm** [comment]
Thanks Angelll. No problems, any help you can offer is much appreciated.

**Comment by pavelthq** [comment]
@gedm , can you just change:

```
$file = isset($_REQUEST['file']) ? $_REQUEST['file'] : '.';
```

to:

```
$file = isset($_REQUEST['file']) ? urldecode($_REQUEST['file']) : '.';
```

**Comment by pavelthq** [comment]
Leave reply if it works

**Comment by gedm** [comment]
Hi Angelll,
fixed.  Thank you very much for spending your time on this. I appreciate it.
