### ISSUE TITLE
Unzip not working?

### ISSUE THREAD

**Issue by tempeleng** [AngeIII/simple-file-manager#3]
I like this fork because it has a lot more functions built-in but unzip doesn't seem to work.
The following edit I did to the original @jcampbell1 version works. Can you fix yours?
(Not familiar enough with Github to send a proper pull request. Sorry.)

Edit: Oh, it actually works but it unzips the files in a new directory. That's easy to modify. Thanks for forking this project :+1: 

`````` 7a8
> error_reporting( error_reporting() & ~E_NOTICE );
53a55
>               'is_zip' => strstr($entry, '.zip'),
68a71,82
> } elseif ($_POST['do'] == 'unzip') {
>     // get the absolute path to $file
>     $path = pathinfo(realpath($file), PATHINFO_DIRNAME);
>     $zip = new ZipArchive;
>     $res = $zip->open($file);
>     if ($res === TRUE) {
>       $zip->extractTo($path);
>       $zip->close();
>     } else {
>       echo "Couldn't open $file";
>     }
>   exit;
241a256,262
>   $('.unzip').live('click',function(data) {
>       $.post("",{'do':'unzip',file:$(this).attr('data-file'),xsrf:XSRF},function(response){
>           list();
>       },'json');
>       return false;
>   });
> 
342a364
>       var $unzip_link = $(' <a href="#" />').attr('data-file',data.path).addClass('unzip').text('unzip');
354c376
<           .append( $('<td/>').append($dl_link).append( data.is_deleteable ? $delete_link : '') )

---
>           .append( $('<td/>').append($dl_link).append( data.is_deleteable ? $delete_link : '' ).append( data.is_zip ? $unzip_link : '' ) )```
``````

**Comment by pavelthq** [comment]
Actually you are right it unzips into a new folder and this is native for most file-managers. 

I'm happy that you found this fork great. 

P.S Note that in production you should not use this kind of file-managers, because it probably makes a security hole for hackers. You should be very careful with access. Add at least `.htpasswd` checks
